### ISSUE TITLE
Thank you for your sharing! Is there any metrics code?

### ISSUE THREAD

**Issue by yiqingHuang0326** [julia0607/Wide-Range-Image-Blending#3]
I am trying to reproduce the value of FID and KID of your program. Is there any metrics code for this program?
I only get the related information from the sentence "crop the central area of size 256 ×512 from the output panorama of size 256 ×768 for performing evaluation and comparison" in your paper, and want to know which pictures to be compared with the test results as well as how to crop the compared pictures.

**Comment by julia0607** [comment]
For FID I'm using the implementation provided [here](https://github.com/mseitzer/pytorch-fid), and for KID I'm using [this](https://github.com/abdulfatir/gan-metrics-pytorch) implementation. 
Basically for both FID and KID, the generated images are compared with random real images, so you can randomly select real images with same size and amount as your generated images. 
For the evaluation provided in our paper, I'm using [these real images](https://drive.google.com/file/d/1Jkno47c5O6yH7RSAmDsgi-O0_nGVIJPW/view?usp=share_link), which are 2649 images with size 256 x 512 cropped from our testing set .

**Comment by yiqingHuang0326** [comment]
Thanks a lot for your reply! 
I am also confused that the amount of pictures in the test folder of the dataset named scenery6000_split only have 1000 images, is the 2649 pictures in the testing set are all cropped from it and how did you crop them?

**Comment by yiqingHuang0326** [comment]
Thanks a lot for your reply!
I am also confused that the amount of pictures in the test folder of the dataset named scenery6000_split only have 1000 images, is the 2649 pictures in the testing set are all cropped from it and how did you crop them?

**Comment by julia0607** [comment]
Yes, all 2649 pictures are cropped from the 1000 testing images.
I randomly cropped multiple patches (each with size 256 x 512) from each testing images that is larger than 256 x 512, and therefore obtaining 2649 patches from those 1000 testing images.
