### ISSUE TITLE
question about kid_score

### ISSUE THREAD

**Issue by yiqingHuang0326** [julia0607/Wide-Range-Image-Blending#4]
Hi :)
For KID, I used the implementation provided by you on the _rand_real_ folder and  the _center-cropped result1-2_ folder.

Honestly, in the beginig, I didn't follow the argument that "Ensure that you have saved both datasets as numpy files", because I found that it can also get final results using the normal absolute path like _python kid_score.py --true /home/wrib/rand_real/ --fake /home/wrib/center_crop_result1-2/_, and I got 0.015 for mean and 0.001 for std.

Then I used the numpy files form of the two folders, and got the same results.

So, I am here to request for more details about the KID score that how did you use the implementation.

**Comment by julia0607** [comment]
Discussed through mail. Batch size is set to 3 by adding `--batch-size 3` in the command of KID evaluation.
